{
    'name': 'IT Management',
    'version': '19.0.6.0.0',
    'summary': 'IT help desk, assets, maintenance, stock parts consumption, '
               'department cost charge-back, access requests and support chat',
    'category': 'Services/IT',
    'author': 'Custom',
    'license': 'LGPL-3',
    'depends': ['base', 'web', 'mail', 'hr', 'stock', 'product', 'purchase', 'account', 'stock_account'],
    'data': [
        'security/ir.model.access.csv',
        'data/sequence_data.xml',
        'data/stock_data.xml',
        'views/it_asset_views.xml',
        'views/it_ticket_views.xml',
        'views/it_ticket_part_views.xml',
        'views/it_support_chat_views.xml',
        'views/it_access_request_views.xml',
        'views/it_notification_views.xml',
        'views/it_dashboard_views.xml',
        'views/it_inventory_views.xml',
        'views/it_asset_advanced_views.xml',
        'views/it_maintenance_views.xml',
        'views/hr_department_views.xml',
        'views/it_department_charge_views.xml',
        'views/it_settings_views.xml',
        'views/it_purchase_views.xml',
        'views/it_stock_report_views.xml',
        'views/it_department_cost_report_views.xml',
        'wizard/department_cost_report_wizard_view.xml',
        'views/it_management_menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'it_management/static/src/js/it_dashboard.js',
            'it_management/static/src/xml/it_dashboard.xml',
            'it_management/static/src/scss/it_dashboard.scss',
        ],
    },
    'application': True,
    'installable': True,
    'auto_install': False,
}